<?php
require_once 'auth_check.php'; require_once 'csrf.php'; require_once __DIR__ . '/app/partials.php'; require_once __DIR__ . '/app/DonationAdminService.php';
$id = positive_int($_GET['id'] ?? null); if ($id === null) redirect_to('donation_ledger.php');
$conn = getDBConnection();
$stmt = $conn->prepare('SELECT d.*,d.donor_name full_name,d.phone donor_phone,d.address donor_address,COALESCE(f.fname,CONCAT(\'Missing foundation #\',d.foundation_id)) foundation_name,COALESCE(verifier.adname,d.verified_by) verified_by_display FROM donations d LEFT JOIN foundations f ON f.fid=d.foundation_id LEFT JOIN admin verifier ON verifier.admin_id=d.verified_by_admin_id WHERE d.id=?'); $stmt->bind_param('i',$id); $stmt->execute(); $donation=$stmt->get_result()->fetch_assoc(); $stmt->close(); if (!$donation) { $conn->close(); redirect_to('donation_ledger.php'); }
$history=$conn->prepare('SELECT h.previous_status,h.new_status,h.note,COALESCE(changer.adname,h.changed_by) changed_by_display,h.changed_at FROM donation_status_history h LEFT JOIN admin changer ON changer.admin_id=h.changed_by_admin_id WHERE h.donation_id=? ORDER BY h.changed_at DESC,h.history_id DESC'); $history->bind_param('i',$id); $history->execute(); $historyRows=$history->get_result(); $csrfToken=generate_csrf_token();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($donation['reference_code']) ?></title><link rel="stylesheet" href="css/addashb.css"><link rel="stylesheet" href="css/admin-workspace.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"></head>
<body><div class="dashboard-container"><?php render_admin_sidebar('ledger'); ?><main class="workspace-content"><header class="workspace-header"><div><h1><?= e($donation['reference_code']) ?></h1><p>Donation record, verification controls, and complete status history.</p></div><a class="button" href="donation_ledger.php"><i class="fas fa-arrow-left"></i> Back to ledger</a></header>
<section class="detail-grid"><div class="detail-card"><small><i class="fas fa-user"></i> Donor</small><strong><?= e($donation['full_name']) ?></strong><br><?= e($donation['donor_phone']) ?><br><?= e($donation['donor_address']) ?></div><div class="detail-card"><small><i class="fas fa-hand-holding-heart"></i> Donation</small><strong><?= number_format((float)$donation['amount'],2) ?> MMK</strong><br><?= e($donation['foundation_name']) ?><br><?= e($donation['payment_method']) ?></div><div class="detail-card"><small><i class="fas fa-check-circle"></i> Current verification</small><strong><?= e($donation['payment_status']) ?></strong><br><?= e($donation['verified_at'] ?: 'Not verified') ?><br><?= e($donation['verified_by_display'] ?: 'Awaiting verification') ?></div></section>
<section class="panel"><h2><i class="fas fa-pen"></i> Update donation status</h2><form action="update_donation_status.php" method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int)$id ?>"><label>Status<select name="status"><?php foreach(DONATION_STATUSES as $item): ?><option value="<?= e($item) ?>"<?= $donation['payment_status'] === $item ? ' selected' : '' ?>><?= e($item) ?></option><?php endforeach; ?></select></label><label class="full-width">Optional note<textarea name="note" maxlength="500" placeholder="Add context for this status update (optional)."></textarea></label><button type="submit"><i class="fas fa-save"></i> Save status update</button></form></section>
<section class="panel"><h2><i class="fas fa-history"></i> Status history</h2><div class="table-wrap"><table class="workspace-table"><thead><tr><th>When</th><th>Change</th><th>Admin</th><th>Note</th></tr></thead><tbody><?php if ($historyRows->num_rows === 0): ?><tr><td colspan="4">No status history is available yet.</td></tr><?php else: while($row=$historyRows->fetch_assoc()): ?><tr><td><?= e($row['changed_at']) ?></td><td><?= e($row['previous_status'] ?: 'Created') ?> → <?= e($row['new_status']) ?></td><td><?= e($row['changed_by_display']) ?></td><td><?= e($row['note']) ?></td></tr><?php endwhile; endif; ?></tbody></table></div></section></main></div></body></html>
<?php $history->close(); $conn->close(); ?>
